"""empty message

Revision ID: 2b0174830b84
Revises: ce78d69fa2e
Create Date: 2015-06-09 23:32:08.404277

"""

# revision identifiers, used by Alembic.
revision = '2b0174830b84'
down_revision = 'ce78d69fa2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint(u'users_username_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_username_key', 'users', ['username'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###
