"""empty message

Revision ID: ce78d69fa2e
Revises: 51ee9e408912
Create Date: 2015-06-07 04:06:34.938228

"""

# revision identifiers, used by Alembic.
revision = 'ce78d69fa2e'
down_revision = '51ee9e408912'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'users', ['phone_num'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('competition_events')
    ### end Alembic commands ###
